### ISSUE TITLE
/usr/bin/cpan-upload-tiny is no longer installed

### ISSUE THREAD

**Issue by shlomif** [Leont/cpan-upload-tiny#5]

**Comment by Leont** [comment]
I just released 0.006, that should fix this issue.

**Comment by shlomif** [comment]
On Mon, 23 Apr 2018 09:56:47 +0000 (UTC)
Leon Timmermans <notifications@github.com> wrote:

> I just released 0.006, that should fix this issue.
> 

thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://youtu.be/KxGRhd_iWuE - Never Give Up!!

Only dead fish go with the flow.
    — via Nadav Har’El

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Hi,

On Mon, 23 Apr 2018 09:56:47 +0000 (UTC)
Leon Timmermans <notifications@github.com> wrote:

> I just released 0.006, that should fix this issue.
> 

I tested it and the script is not installed yet. Seems like the name of the dir
is wrong in dist.ini.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://youtu.be/xZLwtc9x4yA - Anime in Real Life!! (Parody)

Sometimes you don’t need to be familiar with a better alternative to know that
something sucks. Take Microsoft Word for example.
    — Shlomi Fish’s friend.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by Leont** [comment]
I should have checked before pressing that release button -_-

**Comment by shlomif** [comment]
On Mon, 23 Apr 2018 11:33:53 +0000 (UTC)
Leon Timmermans <notifications@github.com> wrote:

> I should have checked before pressing that release butten -_-
> 

thanks for the fix in 0.007. Seems to be ok now.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/lecture/C-and-CPP/bad-elements/

Chuck Norris has an Erdős number of -1.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .
